postinst - add conditions for updating /etc/init/securityonion.conf

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -29,6 +29,24 @@ case "$1" in
 		mysql --defaults-file=/etc/mysql/debian.cnf -N -B -e "GRANT INSERT,UPDATE ON securityonion_db.object_mappings TO 'readonly'@'localhost';" || echo "Error updating permissions on Squert object_mappings."
 	fi
 
+	# If necessary, copy /etc/nsm/templates/init/securityonion.conf to /etc/init/securityonion.conf:
+	# If new installation (file does not exist), copy file
+	# If pre-elastic, copy file
+	# If post-elastic, do not copy file
+	INIT="/etc/init/securityonion.conf"
+	TEMPLATE="/etc/nsm/templates/init/securityonion.conf"
+	if ! [ -f ${INIT} ]; then
+		echo "${INIT} does not exist.  Creating ${INIT}."
+		cp ${TEMPLATE} ${INIT} || echo "Error copying ${TEMPLATE} to ${INIT}"
+	else
+		if grep -q "/usr/sbin/so-elastic-start" ${INIT} ; then
+			echo "Elastic Stack installed.  Not updating ${INIT}."
+		else
+			echo "${INIT} is an older version.  Updating ${INIT}."
+			cp ${TEMPLATE} ${INIT} || echo "Error copying ${TEMPLATE} to ${INIT}"
+		fi			
+	fi
+
 	# commenting out the following section because some users rely on sguild debug 2
 	# example: https://github.com/Security-Onion-Solutions/security-onion/wiki/ThirdPartyIntegration
 	# change sguild debug to 1
