Issue 924: NSM: set DEBUG 1 in /etc/sguild/sguild.conf

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -29,6 +29,16 @@ case "$1" in
 		mysql --defaults-file=/etc/mysql/debian.cnf -N -B -e "GRANT INSERT,UPDATE ON securityonion_db.object_mappings TO 'readonly'@'localhost';" || echo "Error updating permissions on Squert object_mappings."
 	fi
 
+	# change sguild debug to 1
+	FILE='/etc/sguild/sguild.conf'
+	if [ -f $FILE ]; then
+		if grep "set DEBUG 2" $FILE >/dev/null 2>&1; then
+			echo "Sguild DEBUG is currently set to 2."
+			echo "Setting sguild DEBUG to 1."
+			sed -i 's|set DEBUG 2|set DEBUG 1|g' $FILE || echo "Error updating $FILE"
+		fi
+	fi
+
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
