issues 944 937 943

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -29,15 +29,17 @@ case "$1" in
 		mysql --defaults-file=/etc/mysql/debian.cnf -N -B -e "GRANT INSERT,UPDATE ON securityonion_db.object_mappings TO 'readonly'@'localhost';" || echo "Error updating permissions on Squert object_mappings."
 	fi
 
+	# commenting out the following section because some users rely on sguild debug 2
+	# example: https://github.com/Security-Onion-Solutions/security-onion/wiki/ThirdPartyIntegration
 	# change sguild debug to 1
-	FILE='/etc/sguild/sguild.conf'
-	if [ -f $FILE ]; then
-		if grep "set DEBUG 2" $FILE >/dev/null 2>&1; then
-			echo "Sguild DEBUG is currently set to 2."
-			echo "Setting sguild DEBUG to 1."
-			sed -i 's|set DEBUG 2|set DEBUG 1|g' $FILE || echo "Error updating $FILE"
-		fi
-	fi
+	#FILE='/etc/sguild/sguild.conf'
+	#if [ -f $FILE ]; then
+	#		if grep "set DEBUG 2" $FILE >/dev/null 2>&1; then
+	#		echo "Sguild DEBUG is currently set to 2."
+	#		echo "Setting sguild DEBUG to 1."
+	#		sed -i 's|set DEBUG 2|set DEBUG 1|g' $FILE || echo "Error updating $FILE"
+	#	fi
+	#fi
 
     ;;
 
