/usr/sbin/broctl - check for root privileges

diff --git a/usr/sbin/broctl b/usr/sbin/broctl
--- a/usr/sbin/broctl
+++ b/usr/sbin/broctl
@@ -1,5 +1,30 @@
 #!/bin/bash
+#
+#    /usr/sbin/broctl - run /opt/bro/bin/broctl as limited user
+#    Copyright (C) 2016 Security Onion Solutions, LLC <https://securityonionsolutions.com>
+#
+#    Authors: Doug Burks
+#
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, version 3 of the License.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
+# Ensure we're running as root
+if [ "$(id -u)" != 0 ]; then
+        echo "ERROR: This script must run as root.  Hint..." 1>&2
+        echo "  sudo $0 $@" 1>&2
+        exit 1
+fi
+
+# /etc/nsm/securityonion.conf defines the limited user that we use for starting broctl
 SO_CONF="/etc/nsm/securityonion.conf"
 
 # Add new Bro entries to SO_CONF if necessary
