remove so-common since it already exists in securityonion-elastic package

diff --git a/usr/sbin/so-clear-backlog b/usr/sbin/so-clear-backlog
--- a/usr/sbin/so-clear-backlog
+++ b/usr/sbin/so-clear-backlog
@@ -1,14 +1,30 @@
 #!/bin/bash
-. /usr/sbin/so-common
 
-. /etc/nsm/securityonion.conf
+# Check for prerequisites
+if [ "$(id -u)" -ne 0 ]; then
+        echo "This script must be run using sudo!"
+        exit 1
+fi
 
-if [ -d /nsm/sensor_data ]; then
-	:
-else
+# Define a banner to separate sections
+banner="========================================================================="
+
+header() {
+        echo
+        printf '%s\n' "$banner" "$*" "$banner"
+}
+
+if ! [ -d /nsm/sensor_data ]; then
 	echo "Not a sensor!  Exiting..."
 	exit 1;
 fi
+
+CONF="/etc/nsm/securityonion.conf"
+if ! [ -f $CONF ]; then
+	echo "$CONF not found!  Exiting..."
+	exit 1;
+fi
+. $CONF
 
 SKIP=0
 
